"""Generate the parts of the docs site that must never drift from the source of truth (0023).

This is **build-time tooling, not part of the shipped package** — it lives at the repo root, outside
`src/araclean`, so it never enters the wheel. It renders three kinds of artifact from their single
source of truth and writes them under `docs/`:

  - **per-profile pages** (`docs/profiles/<name>.md`) — from `araclean`'s assembled `Pipeline`, so a
    page enumerates exactly the steps the profile applies, each labelled with the step's *actual*
    safety class (lossless `encoding_repair` vs lossy `linguistic_folding` / `cleaning`, ADR-0004);
  - the **glossary page** (`docs/glossary.md`) and the **abbreviation include**
    (`docs/includes/abbreviations.md`) — both parsed from `GLOSSARY.md`, so the hover tooltips and
    the rendered glossary cannot drift from the canonical terminology (ADR-0007).

The generated files are committed; `tests/test_docs.py` regenerates in memory and fails if the
committed copy is stale, the same commit-the-output-and-test-it discipline the syrupy snapshots use.
Regenerate after editing a profile or `GLOSSARY.md` with::

    uv run python docs_gen.py
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from araclean.config import ProfileName
from araclean.pipeline import Pipeline
from araclean.safety import SafetyClass
from araclean.steps import Step

REPO_ROOT = Path(__file__).resolve().parent
DOCS_DIR = REPO_ROOT / "docs"
GLOSSARY_PATH = REPO_ROOT / "GLOSSARY.md"

# A standing banner on every generated page, so a reader (or an agent) who lands on the raw markdown
# knows not to hand-edit it. Kept verbatim across artifacts as a uniform, easily-searched marker.
_GENERATED_BANNER = (
    "<!-- GENERATED by docs_gen.py from the source of truth (araclean + GLOSSARY.md). "
    "Do not edit by hand; run `uv run python docs_gen.py`. -->"
)


def step_name(step: Step) -> str:
    """The display name of a step: its registry ``name`` if it has one, else the class name.

    Mirrors `araclean.pipeline`'s own step-naming so a generated page names a step exactly as the
    pipeline's repr/select/audit do (built-in steps expose a ``name`` ClassVar; a custom step is
    named by its class).
    """
    name = getattr(step, "name", None)
    return name if isinstance(name, str) else type(step).__name__


# How each safety class reads in a profile table's "Lossless?" column. Encoding repair is the only
# lossless class; the two lossy classes name *what* they discard (ADR-0004 / ADR-0011).
_LOSSLESS_MARKER: dict[SafetyClass, str] = {
    SafetyClass.ENCODING_REPAIR: "✓ lossless",
    SafetyClass.LINGUISTIC_FOLDING: "✗ lossy — a linguistic distinction",
    SafetyClass.CLEANING: "✗ lossy — non-linguistic noise",
}


def _profile_summary(pipe: Pipeline) -> str:
    """A one-paragraph, audit-derived headline: is the profile lossless, and if not, what it loses.

    Derived from the live safety audit (never hand-written prose about steps), so it cannot claim a
    profile is lossless once a lossy step is added to it.
    """
    report = pipe.audit()
    if report.lossless:
        return (
            "**Lossless — safe to apply by default.** Every step is *encoding repair*: it repairs "
            "the encoding (Unicode form, presentation forms, tatweel, look-alike letters, "
            "whitespace) "
            "without discarding any linguistic signal (ADR-0004)."
        )
    folds = len(report.linguistic_folding)
    cleans = len(report.cleaning)
    repairs = len(report.encoding_repair)
    pieces: list[str] = []
    if folds:
        pieces.append(f"{folds} lossy *linguistic folding* step{'s' if folds != 1 else ''}")
    if cleans:
        pieces.append(f"{cleans} *cleaning* step{'s' if cleans != 1 else ''}")
    lossy = " and ".join(pieces)
    return (
        f"**Lossy — opt-in.** Alongside {repairs} lossless encoding-repair steps it applies "
        f"{lossy} that discard information, so it is never the default (ADR-0004)."
    )


def render_profile_page(profile_name: str) -> str:
    """Render the markdown page for one named profile from its *assembled* pipeline.

    The step table is built by walking `Pipeline.from_profile(name).steps` in order, so it reflects
    the real assembled pipeline (duplicated steps and all), and each row is labelled with the step's
    own `safety` class — the cross-check `tests/test_docs.py` pins against the live pipeline.
    """
    canonical = ProfileName(profile_name).value
    pipe = Pipeline.from_profile(canonical)
    lines = [
        _GENERATED_BANNER,
        "",
        f"# `{canonical.upper()}` profile",
        "",
        _profile_summary(pipe),
        "",
        "It assembles these steps, in order:",
        "",
        "| # | Step | Safety | Lossless? |",
        "|---|------|--------|-----------|",
    ]
    for index, step in enumerate(pipe.steps, start=1):
        safety = step.safety
        lines.append(
            f"| {index} | `{step_name(step)}` | `{safety.value}` | {_LOSSLESS_MARKER[safety]} |"
        )
    lines += [
        "",
        "See the [API reference](../reference.md) for what each step does and how to configure it.",
        "",
    ]
    return "\n".join(lines)


@dataclass(frozen=True, slots=True)
class GlossaryEntry:
    """One row of `GLOSSARY.md`'s terminology mapping: the canonical term and its English gloss."""

    term: str
    arabic: str
    english: str


def _strip_markdown(cell: str) -> str:
    """Reduce a glossary table cell to plain text: drop bold/italic/code markers and `<!-- -->`."""
    text = re.sub(r"<!--.*?-->", "", cell)
    text = text.replace("**", "").replace("`", "")
    return text.strip()


def parse_glossary(markdown: str) -> list[GlossaryEntry]:
    """Parse the `## Mapping` terminology table of `GLOSSARY.md` into structured entries.

    Reads only the canonical-terminology table (term | Arabic | English | code points | notes),
    ignoring the project's own coined-terms table below it, so the result is exactly the Arabic
    terms that need a hover gloss.
    """
    entries: list[GlossaryEntry] = []
    in_table = False
    for line in markdown.splitlines():
        if line.startswith("| Term (canonical)"):
            in_table = True
            continue
        if not in_table:
            continue
        if not line.startswith("|"):
            break  # the table ended
        if set(line.replace("|", "").strip()) <= {"-", ":", " "}:
            continue  # the |---|---| separator row
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        term = _strip_markdown(cells[0])
        arabic = _strip_markdown(cells[1])
        english = _strip_markdown(cells[2])
        if term:
            entries.append(GlossaryEntry(term=term, arabic=arabic, english=english))
    return entries


def _abbreviation_keys(term: str) -> list[str]:
    """The lookup keys a term should resolve under for hover tooltips.

    Splits a combined row (``Fatha / Damma / Kasra / Sukun``) into its parts, drops a parenthetical
    (``Harakat (sing. haraka)`` → ``Harakat``), and adds an all-lowercase variant of each so a term
    matches whether it opens a sentence (``Tashkeel``) or sits mid-sentence (``tashkeel``). Ordered,
    de-duplicated.
    """
    base = re.sub(r"\(.*?\)", "", term)
    keys: list[str] = []
    for part in base.split("/"):
        cleaned = part.strip()
        if not cleaned:
            continue
        for candidate in (cleaned, cleaned.lower()):
            if candidate not in keys:
                keys.append(candidate)
    return keys


def render_abbreviations(entries: list[GlossaryEntry]) -> str:
    """Render mkdocs-material abbreviation definitions (`*[Term]: gloss`) from glossary entries.

    Auto-appended to every page (via the pymdownx.snippets `auto_append`), so each Arabic term shows
    its English gloss on hover wherever it appears — generated from `GLOSSARY.md`, never hand-kept.
    """
    lines = [_GENERATED_BANNER, ""]
    seen: set[str] = set()
    for entry in entries:
        if not entry.english:
            continue
        for key in _abbreviation_keys(entry.term):
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"*[{key}]: {entry.english}")
    return "\n".join(lines) + "\n"


def render_glossary_page(entries: list[GlossaryEntry]) -> str:
    """Render the docs glossary page: a clean term ↔ Arabic ↔ English table from `GLOSSARY.md`.

    Rendered fresh (rather than including the raw `GLOSSARY.md`, whose internal repo links would
    break a strict build) so the published glossary stays in lock-step with the canonical source.
    """
    lines = [
        _GENERATED_BANNER,
        "",
        "# Glossary",
        "",
        "araclean uses **Arabic-primary terminology** (ADR-0007): the canonical name of each "
        "Arabic-script entity is its established transliteration, glossed to English here "
        "and shown as a hover tooltip wherever it appears in these docs.",
        "",
        "| Term | Arabic | English / technical |",
        "|------|--------|---------------------|",
    ]
    for entry in entries:
        lines.append(f"| {entry.term} | {entry.arabic} | {entry.english} |")
    lines.append("")
    return "\n".join(lines)


def generated_files() -> dict[Path, str]:
    """Map every generated docs file to a fresh render of it from the source of truth."""
    entries = parse_glossary(GLOSSARY_PATH.read_text(encoding="utf-8"))
    files: dict[Path, str] = {
        DOCS_DIR / "glossary.md": render_glossary_page(entries),
        DOCS_DIR / "includes" / "abbreviations.md": render_abbreviations(entries),
    }
    for member in ProfileName:
        files[DOCS_DIR / "profiles" / f"{member.value}.md"] = render_profile_page(member.value)
    return files


def main() -> None:
    """Write every generated docs file to disk (run after editing a profile or `GLOSSARY.md`)."""
    for path, content in generated_files().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
